export const settings = {
  brands: [
    {
      API_URL: 'https://chevignon.myvtex.com/api/oms/pvt/orders',
      brand: 'Chevignon',
      apiKey: process.env.API_KEY_CHE,
      apiToken: process.env.API_TOKEN_CHE,
      cedi: 'chevignoncedi',
    },
    {
      API_URL: 'https://nafnaf.myvtex.com/api/oms/pvt/orders',
      brand: 'Naf Naf',
      apiKey: process.env.API_KEY_NAF,
      apiToken: process.env.API_TOKEN_NAF,
      cedi: 'nafnafcedi',
    },
    {
      API_URL: 'https://americaneagle.myvtex.com/api/oms/pvt/orders',
      brand: 'AEO',
      apiKey: process.env.API_KEY_AEO,
      apiToken: process.env.API_TOKEN_AEO,
      cedi: 'americaneaglecedi',
    },
    {
      API_URL: 'https://lukshop.myvtex.com/api/oms/pvt/orders',
      brand: 'Rifle',
      apiKey: process.env.API_KEY_RIFLE,
      apiToken: process.env.API_TOKEN_RIFLE,
      cedi: 'lukshopcedi',
    },
    {
      API_URL: 'https://esprit.myvtex.com/api/oms/pvt/orders',
      brand: 'Esprit',
      apiKey: process.env.API_KEY_ESP,
      apiToken: process.env.API_TOKEN_ESP,
      cedi: 'espritcedi',
    },
    {
      API_URL: 'https://kliiker.myvtex.com/api/oms/pvt/orders',
      brand: 'Kliiker',
      apiKey: process.env.API_KEY_KLIIKER,
      apiToken: process.env.API_TOKEN_KLIIKER,
      cedi: 'kliiker',
    },
    {
      API_URL: 'https://americanino.myvtex.com/api/oms/pvt/orders',
      brand: 'Americanino',
      apiKey: process.env.API_KEY_AME,
      apiToken: process.env.API_TOKEN_AME,
      cedi: 'americaninocedi',
    },
    {
      API_URL: 'https://vivant.myvtex.com/api/oms/pvt/orders',
      brand: 'Vivant',
      apiKey: process.env.API_KEY_VIVANT,
      apiToken: process.env.API_TOKEN_VIVANT,
      cedi: 'vivantcedi',
    },
  ],
}
